version: '3.8'

services:
  llama-rpc-server:
    image: ghcr.io/ggerganov/llama.cpp:server
    ports:
      - "50051:50051"
    volumes:
      - /models:/cluster/models
    environment:
      - MODEL_PATH=/models/Meta-Llama-3.1-8B-Instruct-Q6_K_L.gguf
      - RPC=50051
